# Generated by Django 4.0.3 on 2022-04-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal_time',
            field=models.CharField(default='None specified', max_length=100),
        ),
    ]
