# Generated by Django 4.0.3 on 2022-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_due_date_remove_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal_time',
            field=models.CharField(default='SOME_STRING', max_length=100),
        ),
    ]
