# Generated by Django 4.0.3 on 2022-04-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_goal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal_time',
            field=models.CharField(default='None Specified', max_length=100),
        ),
    ]
