# Generated by Django 4.0.3 on 2022-04-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B-flat/A#', 'B-flat/A#'), ('B', 'B'), ('C', 'C'), ('C#/D-flat', 'C#/D-flat'), ('D', 'D'), ('E-flat/D#', 'E-flat/D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('A-flat/G#', 'A-flat/G#')], default='A', max_length=20),
        ),
    ]
